return {
    -- {
    --     "saghen/blink.cmp",
    --     ---@module 'blink.cmp'
    --     ---@type blink.cmp.Config
    --     opts = {
    --         sources = {
    --             compat = {},
    --             default = { "lsp", "path", "snippets", "buffer" },
    --             providers = {
    --                 snippets = {
    --                     min_keyword_length = 2,
    --                     score_offset = 4,
    --                 },
    --                 lsp = {
    --                     min_keyword_length = 3,
    --                     score_offset = 3,
    --                 },
    --                 path = {
    --                     min_keyword_length = 3,
    --                     score_offset = 2,
    --                 },
    --                 buffer = {
    --                     min_keyword_length = 5,
    --                     score_offset = 1,
    --                 },
    --             },
    --         },
    --
    --         keymap = {
    --             preset = "enter",
    --             ["<C-y>"] = { "select_and_accept" },
    --         },
    --     },
    -- },
}
